// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnrercflzcudlhzesxzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZucmVyY2ZsemN1ZGxoemVzeHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MjU5MzksImV4cCI6MjA2MDAwMTkzOX0.GqdPanDjLC2kxgvTR0rNa0Dd8txfAfwlHMs4VMx11xc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);